### PR TITLE
Best file ever

### PR DESCRIPTION
**Pull request by Blankf**
:100: this is the best file i've written in a while :100: 
- [x] This is step 1
- [ ] This is step 2

### CODE REVIEW

**Comment by rsegers** [comment]
:beers:

**Comment by Larsmannetje** [comment]
:+1: :beer: :beers: :clock5:

**Comment by Larsmannetje** [comment]
It deserves to be merged.

**Comment by rsegers** [comment]
@Larsmannetje @Blankf why isn't this merged yet?! :angry:

**Comment by githubteacher** [comment]
Sorry! :sweat_smile:  merging now!

**Pull request merged**
